pipeline {
    agent any
    tools {
        jdk 'jdk8'
        maven 'maven-3.6.1'
    }
    stages {

        // Build the remaining Java services and the rewritten Go/Python services.
        stage('Build') {
            steps {
                echo "Polyglot build..."
                sh 'command -v go && command -v uv'
                sh 'make package'
                echo "Package Successful!"

                script {
                    if (env.BRANCH_NAME == 'master') {
                        echo "Docker Building..."
                        // sh 'sudo /usr/local/bin/docker-compose build'
                        echo "Building images Successful!"

                        echo "Pushing images..."
                        withCredentials([usernamePassword(credentialsId: 'dockerHub-codewisdom', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                            sh "sudo docker login -u ${dockerHubUser} -p ${dockerHubPassword}"
                            // sh "sudo /bin/bash ./jenkins-ci/image-tag-push.sh"
                        }
                        echo "Push Successful"
                    } else {
                        echo "This isn't the master branch. Skip the docker building & pushing step!"
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo "P3C-PMD"
                sh "mvn pmd:pmd"

                echo "Unit Test..."
                sh 'make test'
                echo "Test Successful"
	
                jacoco(
                    execPattern: '**/target/jacoco.exec',
                    classPattern: '**/target/classes',
                    sourcePattern: '**/src/main/java',
                    exclusionPattern: '**/src/test*',
                    changeBuildStatus: true
                )
            }
        }

    }
	
    post {
        always {
            pmd(canRunOnFailed: true, pattern: '**/target/pmd.xml')
            junit testResults: "**/target/surefire-reports/*.xml"
            sh 'sudo /bin/bash ./jenkins-ci/clean.sh'
        }
        failure {
            mail from : 'jenkinsx@163.com',
            to : '1989153584@qq.com',
            subject : "Failed Pipeline: ${currentBuild.fullDisplayName} :(",
            body : "Something is wrong with ${env.BUILD_URL}"
        }
    }
}
